#Lab 4

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

In [ ]:
print(df.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.shape

(150, 6)

In [ ]:
df.tail

<bound method NDFrame.tail of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [ ]:
df.tail(n=1)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.loc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [ ]:
df.loc[20]

Id                        21
SepalLengthCm            5.4
SepalWidthCm             3.4
PetalLengthCm            1.7
PetalWidthCm             0.2
Species          Iris-setosa
Name: 20, dtype: object

In [ ]:
df.loc[149]

Id                          150
SepalLengthCm               5.9
SepalWidthCm                3.0
PetalLengthCm               5.1
PetalWidthCm                1.8
Species          Iris-virginica
Name: 149, dtype: object

In [ ]:
print(df.loc[[0, 99, 149]])

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
99   100            5.7           2.8            4.1           1.3
149  150            5.9           3.0            5.1           1.8

             Species
0        Iris-setosa
99   Iris-versicolor
149   Iris-virginica

In [ ]:
df.iloc[[-1,149]]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
149,150,5.9,3.0,5.1,1.8,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
subset=df.loc[:,["SepalLengthCm","SepalWidthCm"]]
subset.head()

   SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6

In [ ]:
subset2=df.iloc[:,[2,4]]
print(subset2.head())

   SepalWidthCm  PetalWidthCm
0           3.5           0.2
1           3.0           0.2
2           3.2           0.2
3           3.1           0.2
4           3.6           0.2

In [ ]:
list1 = df.iloc[:, :6].values.tolist()
print(list1[:5]) # Print first 5 rows to check

[[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'], [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'], [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa']]

In [ ]:
list2=list(range(5))

In [ ]:
subset3=df.iloc[:,list2]
subset3.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [ ]:
print(df.iloc[[0,99,149],[0,3,5]])

      Id  PetalLengthCm          Species
0      1            1.4      Iris-setosa
99   100            4.1  Iris-versicolor
149  150            5.1   Iris-virginica

In [ ]:
print(df.isnull().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.loc[10:15,"SepalLengthCm"]=np.nan
df.loc[20:25,"PetalWidthCm"]=np.nan
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    6
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     6
Species          0
dtype: int64

In [ ]:
#Filling missing values either by mean median
df["SepalLengthCm"].fillna(df["SepalLengthCm"].mean(),inplace=True)

/tmp/ipython-input-853769988.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SepalLengthCm"].fillna(df["SepalLengthCm"].mean(),inplace=True)

In [ ]:

df.loc[10:15,"SepalLengthCm"]

10    5.872917
11    5.872917
12    5.872917
13    5.872917
14    5.872917
15    5.872917
Name: SepalLengthCm, dtype: float64

In [ ]:
df["PetalWidthCm"].fillna(df["PetalWidthCm"].median(),inplace=True)
df.loc[20:25,"PetalWidthCm"]

/tmp/ipython-input-1038998667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["PetalWidthCm"].fillna(df["PetalWidthCm"].median(),inplace=True)

20    1.35
21    1.35
22    1.35
23    1.35
24    1.35
25    1.35
Name: PetalWidthCm, dtype: float64

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.rename(columns={"SepalLengthCm":"SL"},inplace=True)
df.head()

   Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1  5.1           3.5            1.4           0.2  Iris-setosa
1   2  4.9           3.0            1.4           0.2  Iris-setosa
2   3  4.7           3.2            1.3           0.2  Iris-setosa
3   4  4.6           3.1            1.5           0.2  Iris-setosa
4   5  5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df["SL"]=df["SL"].astype(float)
df["PetalWidthCm"]=df["PetalWidthCm"].astype(float)

In [ ]:
print(df.info(),df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None    Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1  5.1           3.5            1.4           0.2  Iris-setosa
1   2  4.9           3.0            1.4           0.2  Iris-setosa
2   3  4.7           3.2            1.3           0.2  Iris-setosa
3   4  4.6           3.1            1.5           0.2  Iris-setosa
4   5  5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.iloc[:,-1]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
df["Species"].replace({"Iris-sentosa":0,"Iris-virginica":1})

#Linear Regression

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Iris.csv")

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

In [ ]:
df["Species"] = df["Species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
})

/tmp/ipython-input-1910832043.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"] = df["Species"].replace({

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [ ]:
X_lr = df[["SepalLengthCm", "SepalWidthCm", "PetalWidthCm"]]
y_lr = df["PetalLengthCm"]

In [ ]:
X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_lr, y_lr, test_size=0.2, random_state=42)

In [ ]:
# Train Linear Regression Model
lr_model = LinearRegression()

In [ ]:
lr_model.fit(X_train_lr, y_train_lr)

LinearRegression()

In [ ]:
# Predictions
y_pred_lr = lr_model.predict(X_test_lr)

In [ ]:
# Evaluate Linear Regression Model
print("LINEAR REGRESSION EVALUATION")
print("Mean Squared Error:", mean_squared_error(y_test_lr, y_pred_lr))
print("Mean Absolute Error:", mean_absolute_error(y_test_lr, y_pred_lr))
print("R2 Score:", r2_score(y_test_lr, y_pred_lr))

LINEAR REGRESSION EVALUATION
Mean Squared Error: 0.12991981605759947
Mean Absolute Error: 0.2606173239288886
R2 Score: 0.9603587427485161

#Logistic Regression

In [ ]:
# For LOGISTIC REGRESSION (Classification – Predicting Iris Species)

# Prepare Data for Logistic Regression
X = df.drop(columns=["Species"])
y = df["Species"]

In [ ]:
# Train–Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Train Logistic Regression Model
log_model = LogisticRegression(max_iter=200)
log_model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [ ]:
# Predictions
y_pred_log = log_model.predict(X_test)

In [ ]:
#  Evaluate Logistic Regression Model
print("\nLOGISTIC REGRESSION EVALUATION")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))

LOGISTIC REGRESSION EVALUATION
Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30